all:
  children:
    routers:
      hosts:
        lablsbng1:
          ansible_host: 192.168.230.246
        lablscpe1:
          ansible_host: 192.168.230.69
  vars:
    ansible_user: mcgmbh
    ansible_password: "{{ vault_ansible_password }}"
    ansible_become: false
    ansible_connection: ansible.netcommon.network_cli
    ansible_ssh_common_args: "-o PubkeyAuthentication=no -o PreferredAuthentications=password -o IdentitiesOnly=yes"
    ansible_network_os: community.network.routeros
